<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class AdvanceSalaryRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'needed_by' => 'required',
            'amount' => 'required',
            'reason' => 'required',
        ];
    }
    public function messages()
    {
        return [
            'needed_by.required' => 'Date is required.',
            'amount.required' => 'Amount is required.',
            'reason.required' => 'Reason is required.',
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        //dd($validator->errors()->all());
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
