<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class StoreAttendanceRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'entry_time' => 'required|date_format:H:i',
            'exit_time' => 'nullable|date_format:H:i',
            'date' => 'required|date',
            'reason' => 'required|string|max:255',
        ];
    }
    public function messages(): array
    {
        return [
            'entry_time.required' => 'Entry time is required.',
            'entry_time.date_format' => 'Entry time format is invalid.',
            'date.required' => 'Date is required.',
            'date.date_format' => 'Date format is invalid.',
            'reason.required' => 'Reason is required.',
            'reason.string' => 'Reason is invalid.',
            'reason.max' => 'Reason is too long.',

        ];
    }
    protected function failedValidation(Validator $validator)
    {
        //dd($validator);
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
