<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class StoreDepartmentLeadRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'employee_id' => 'required|exists:employees,id',
            'department_id' => 'required|exists:departments,id',
        ];
    }
    public function messages(): array
    {
        return [
            'employee.required' => 'Employee ID is required.',
            'employee.exists' => 'Employee ID is invalid.',

        ];
    }
    public function failedValidation(Validator $validator)
    {
        //d($validator->errors()->all());
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
