<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class UserUpdateRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'department' => 'required|string|max:255',
            'status' => 'required|in:active,inactive',
            'role' => 'required|string|exists:roles,name',
        ];
    }

    public function messages()
    {
        return [
            'department.required' => 'Please select a department.',
            'status.required' => 'Status field is mandatory.',
            'status.in' => 'Status must be either active or inactive.',
            'role.required' => 'Please assign a role to the user.',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        //dd($validator->errors()->all());
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
