<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class LoanClaimRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'amount' => 'required|numeric|min:0',
            'payment_method' => 'required|in:Bank Transfer,Cash,Cheque',
            'duration_months' => 'required|integer|min:1',
            'start_month' => 'required|string',
            'start_year' => 'required|integer',
            'purpose' => 'required|string|max:1000',
        ];
    }

    public function messages()
    {
        return [
            'amount.required' => 'Amount is required.',
            'amount.numeric' => 'Amount must be a number.',
            'amount.min' => 'Amount must be a positive number.',
            'payment_method.required' => 'Payment method is required.',
            'payment_method.in' => 'Payment method must be one of Bank Transfer.',
            'duration_months.required' => 'Duration months is required.',
            'start_month.required' => 'Start month is required.',
            'start_year.required' => 'Start year is required.',
            'start_year.required' => 'Start year is required.',
            'purpose.required' => 'Purpose is required.',
            'purpose.required' => 'Purpose is required.',
        ];
    }

    public function response(array $errors)
    {
        return response()->json($errors, 422);
    }

    public function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
