<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class UserCreateRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'employee_id' => 'required|exists:employees,id',
            'username' => 'required',
            'password' => 'required|min:6',
            'password_confirmation' => 'required|same:password',
            'role' => 'required',
        ];
    }
    public function messages()
    {
        return [
            'username.required' => 'Username cannot be empty',
            'password.required' => 'password cannot be empty',
            'password.min' => 'Password minimal 6 character',
            'password_confirmation.required' => 'Confirm Password cannot be empty',
            'password_confirmation.same' => 'Confirm Password with the same password',
            'role.required' => 'Role cannot be empty',

        ];
    }
   public function failedValidation(Validator $validator)
   {
       // TODO: Change the autogenerated stub
       dd($validator->errors()->all());
   }

}
